// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHjnMDcj6Sb1R7W6e2hgM5zc32W9Msp90',
    appId: '1:809447462696:web:09cfce524c868e65fce21d',
    messagingSenderId: '809447462696',
    projectId: 'ai-trolley-f8b2e',
    authDomain: 'ai-trolley-f8b2e.firebaseapp.com',
    storageBucket: 'ai-trolley-f8b2e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3R-XBbJj36uzo8Z4JNJW8oxIoFgUNuF4',
    appId: '1:809447462696:android:321c1d26dcf8c1bffce21d',
    messagingSenderId: '809447462696',
    projectId: 'ai-trolley-f8b2e',
    storageBucket: 'ai-trolley-f8b2e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHjnMDcj6Sb1R7W6e2hgM5zc32W9Msp90',
    appId: '1:809447462696:web:68ac0651c21d065bfce21d',
    messagingSenderId: '809447462696',
    projectId: 'ai-trolley-f8b2e',
    authDomain: 'ai-trolley-f8b2e.firebaseapp.com',
    storageBucket: 'ai-trolley-f8b2e.firebasestorage.app',
  );
}
